version: '3'
services:
   mint_service:
     image: mint_service
     ports:
       - 8080:8080
     links:
       - mongo
     depends_on:
       - mongo
   app_service:
     image: app_service
     ports:
       - 8081:8081
     links:
       - mongo
     depends_on:
       - mongo
   mongo:
     image: mongo:latest
     ports:
       - 27017:27017
     volumes:
       - './dev/data/db:/data/db'